version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: chilling-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: chilling_stories_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ~/story-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: story-server
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: chilling_stories_db
      PORT: 8000
    volumes:
      - .:/app
      - /app/node_modules
      - ~/story-data/assets/posters:/app/assets/images/poster/stories
      - ~/story-data/assets/images/users/avatars:/app/assets/images/users/avatars