deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Configure SSH for Cloudflare Tunnel
        run: |
          mkdir -p ~/.ssh
          echo "Host ${{ secrets.SSH_HOST }}
            ProxyCommand /usr/bin/cloudflared access ssh --hostname %h" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ChillingStories_Server || git clone https://github.com/PhongDayNai/ChillingStories_Server.git ~/ChillingStories_Server
            cd ~/ChillingStories_Server
            git pull origin main
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            docker-compose up -d --build
            docker image prune -f